# Generated by Django 3.2.3 on 2021-07-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
