# Generated by Django 3.2.3 on 2021-07-27 12:27

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('videos', '0002_videomodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
