# Generated by Django 3.2.3 on 2021-08-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Video',
            new_name='video',
        ),
    ]
